title: Anbuvenkatesh A
description: Software Engineer at Temenos India Pvt Ltd. Passionate on software development; Fascinated by technology; Thriving to learn and explore everyday. Experience in developing and maintaining products for core banking system. Proven ability to leverage full-stack knowledge and experience to build high performant distributed system that can scale. Extensive expertise in microservice architecture development using REST and event driven methodology, across various cloud platform and for on-premise.
show_downloads: true
google_analytics: false
theme: jekyll-theme-cayman
